//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Area
    {
        public TB_Area()
        {
            this.TB_Grupo = new HashSet<TB_Grupo>();
        }
    
        public int IdArea { get; set; }
        public int IdEmpresa { get; set; }
        public string Descricao { get; set; }
        public string Sigla { get; set; }
    
        public virtual TB_Empresa TB_Empresa { get; set; }
        public virtual ICollection<TB_Grupo> TB_Grupo { get; set; }
    }
}
