//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Grupo
    {
        public TB_Grupo()
        {
            this.TB_GrupoPerfil = new HashSet<TB_GrupoPerfil>();
            this.TB_Usuario = new HashSet<TB_Usuario>();
        }
    
        public int IdGrupo { get; set; }
        public int IdEmpresa { get; set; }
        public string Descricao { get; set; }
        public string Sigla { get; set; }
        public int IdArea { get; set; }
    
        public virtual TB_Area TB_Area { get; set; }
        public virtual TB_Empresa TB_Empresa { get; set; }
        public virtual ICollection<TB_GrupoPerfil> TB_GrupoPerfil { get; set; }
        public virtual ICollection<TB_Usuario> TB_Usuario { get; set; }
    }
}
