//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_GrupoPerfil
    {
        public int IdGrupo { get; set; }
        public int IdEmpresa { get; set; }
        public int IdMenu { get; set; }
        public Nullable<bool> Bloqueado { get; set; }
        public Nullable<bool> Todos { get; set; }
        public Nullable<bool> Pesquisa { get; set; }
        public Nullable<bool> Inclusao { get; set; }
        public Nullable<bool> Alteracao { get; set; }
        public Nullable<bool> Delecao { get; set; }
        public Nullable<bool> Impressao { get; set; }
        public Nullable<bool> Exportacao { get; set; }
    
        public virtual TB_Empresa TB_Empresa { get; set; }
        public virtual TB_Grupo TB_Grupo { get; set; }
        public virtual TB_Menu TB_Menu { get; set; }
    }
}
