//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Menu
    {
        public TB_Menu()
        {
            this.TB_GrupoPerfil = new HashSet<TB_GrupoPerfil>();
        }
    
        public int IdMenu { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Caption { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public string URL { get; set; }
        public Nullable<bool> Seguranca { get; set; }
        public Nullable<bool> Menu { get; set; }
        public Nullable<int> Ordem { get; set; }
    
        public virtual TB_Empresa TB_Empresa { get; set; }
        public virtual ICollection<TB_GrupoPerfil> TB_GrupoPerfil { get; set; }
    }
}
